package app.fjj.stun.service

import app.fjj.stun.core.BuildConfig

/**
 * tproxy 模式的两份配置文件生成器。
 *
 * 这两份配置**格式完全不同、消费方也不同**，原先却是两个同名重载
 * `buildHevSocks5TProxyConfig(...)`，只靠参数类型区分 —— 读代码时看到
 * `buildHevSocks5TProxyConfig(context, TPROXY_PORT, TPROXY_PORT, DNS_HIJACK_PORT)` 根本分不清
 * 自己拿到的是 shell 变量还是 YAML。现在按"谁消费它"命名：
 *
 * | 函数 | 写到哪 | 谁消费 | 格式 |
 * |---|---|---|---|
 * | [buildShellRules] | `cacheDir/tproxy_rules.conf` | `tproxy.sh` 第 172 行 `. `（source） | shell 变量赋值 |
 * | [buildCoreYaml] | `cacheDir/hev-socks5-tproxy.conf` | `hev-socks5-tproxy` 命令行 | YAML |
 *
 * 两个函数都不再接收 `Context` / `Profile`：它们一个都没用到（DNS 段在 YAML 里是注释状态，
 * profile 级调参目前不存在），去掉之后整个类变成纯函数，能被纯 JVM 单测直接断言 ——
 * 这在 tproxy 这条链上是第一次有测试覆盖。
 *
 * 可见性是 `internal`：全仓库只有 `MyTransparentProxyService` 用它（已跨模块确认），
 * 而它的入参 `AppFilter` 是 internal，收窄后不必把整个模型公开出去。
 */
internal object TransparentProxyConfigBuilder {

    /**
     * 生成 `tproxy.sh` 的 shell 变量配置。
     *
     * @param selfPackage 本 App 包名。**必须直连**，否则自己的流量会被 TPROXY 重新灌回
     *   `hev-socks5-tproxy` 形成死循环。两种模式的处理位置不同，见下方注释。
     * @param tproxyPort tproxy 监听端口，tcp / udp 共用（`hev-socks5-tproxy` 的 yaml 也是同一端口）
     * @param dnsPort DNS 劫持重定向端口
     * @param appFilter 分应用代理配置，[AppFilter.EMPTY] 表示不过滤
     */
    fun buildShellRules(
        selfPackage: String,
        tproxyPort: Int,
        dnsPort: Int,
        appFilter: AppFilter,
    ): String {
        // 与 tproxy.sh `setup_proxy_chain` 的两条链语义对齐（不是照字面翻译，是照行为）：
        //  - blacklist：列进 BYPASS_APPS_LIST 的 uid → `-j ACCEPT`（终止遍历 = 直连）；
        //    链尾 `-j RETURN`，其余包继续往下走 → 被 TPROXY 代理。
        //    所以 blacklist 的 BYPASS_APPS_LIST == Stun 的「这些应用不走代理」。
        //  - whitelist：列进 PROXY_APPS_LIST 的 uid → `-j RETURN`（继续遍历 → 被代理）；
        //    链尾 `-j ACCEPT`，**其余全部直连**。所以 whitelist 的 PROXY_APPS_LIST == Stun 的
        //    「只有这些应用走代理」。注意这条分支**完全不读** BYPASS_APPS_LIST。
        //
        // 自己必须直连：blacklist 下把自己钉进 bypass 列表；whitelist 下则只能把自己从
        // proxy 列表剔掉，靠链尾那个 `-j ACCEPT` 兜住（把 `user:` 前缀形式也认出来，
        // 否则用户手填 `0:app.fjj.stun` 就会把自己送进死循环）。
        val selected = appFilter.packages.filterNot { it == selfPackage || it == "0:$selfPackage" }
        val isAllowList = appFilter.isAllowList
        val proxyApps = if (isAllowList) selected.joinToString(" ") { "0:$it" } else ""
        val bypassApps = if (isAllowList) {
            ""
        } else {
            (listOf(selfPackage) + selected).joinToString(" ") { "0:$it" }
        }

        return """
            # Auto-generated by TransparentProxyConfigBuilder — 请勿手改，重新连接时会覆盖
            PROXY_TCP_PORT=$tproxyPort
            PROXY_UDP_PORT=$tproxyPort
            PROXY_MODE=1
            DNS_HIJACK_ENABLE=1
            DNS_PORT=$dnsPort
            BLOCK_QUIC=0
            BYPASS_CN_IP=0
            CN_IP_URL=https://push.4544.de/https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt
            CN_IPV6_URL=https://push.4544.de/https://ispip.clang.cn/all_cn_ipv6.txt
            BYPASS_IPv4_LIST="127.0.0.0/8"
            BYPASS_IPv6_LIST="::1/128"
            PROXY_IPV6=1
            APP_PROXY_ENABLE=1
            APP_PROXY_MODE=${if (isAllowList) "whitelist" else "blacklist"}
            BYPASS_APPS_LIST="$bypassApps"
            PROXY_APPS_LIST="$proxyApps"
            DRY_RUN=0
        """.trimIndent()
    }

    /**
     * 生成 `hev-socks5-tproxy` 的 YAML 配置（root 模式下由命令行直接读文件）。
     *
     * 目前只有日志级别随构建类型变；tproxy 侧没有 per-profile 的 core 调参，所以不收 `Profile`。
     * DNS 段保持注释：tproxy.sh 已经在 mangle 表里做了 DNS 劫持，core 再开一个 dns 段会与之冲突。
     */
    fun buildCoreYaml(socksPort: Int, tproxyPort: Int): String {
        return """
            main:
              workers: 1
            misc:
              log-level: ${if (BuildConfig.DEBUG) "debug" else "warn"}
            tcp:
              port: $tproxyPort
              address: '::' # Listen on all interfaces (IPv4/IPv6)
            udp:
              port: $tproxyPort
              address: '::'
            socks5:
              port: $socksPort
              address: '127.0.0.1'
              udp: udp
        """.trimIndent()
    }
}
